application: crudangular
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /
  static_files: mainFuncionario.html
  upload: mainFuncionario.html

- url: /mainFuncionario.html
  static_files: mainFuncionario.html
  upload: mainFuncionario.html

- url: /mainDepto.html
  static_files: mainDepto.html
  upload: mainDepto.html

- url: /mainCargo.html
  static_files: mainCargo.html
  upload: mainCargo.html